### ISSUE TITLE
Dark mode in Colab: table rows not visible 

### ISSUE THREAD

**Issue by etowahadams** [manzt/quak#45]
When Google colab notebook is in dark mode, the table row text is hard to see. 
<img width="742" alt="image" src="https://github.com/user-attachments/assets/4d72fb0d-315c-43d7-8413-5558cd690bcd">

On hover, it looks great though!
<img width="708" alt="image" src="https://github.com/user-attachments/assets/6d9c6697-00bb-4287-a2f2-aa0c98253d5d">

Looks like Colab uses `html[theme=dark]` selector so perhaps it could be used to switch to a dark mode. 
https://github.com/googlecolab/colabtools/issues/1214#issuecomment-624716998

**Comment by manzt** [comment]
Oooo this could definitely be improved. Thanks for reporting! 

There has been another request for theming, and for right now I've decided it's out of scope. I think we could come up with something comprehensive using CSS variables, but my priority would be to get the table as is rendering consistently across environments.

For now, I'll make a fix to set a background color so that the background isn't inherited. As a follow up, I'll look into a dark/light mode.
